# Generated by Django 4.2.7 on 2023-11-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('department', models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resource'), ('BS', 'Business')], max_length=30)),
                ('leave_from', models.CharField(max_length=30)),
                ('leave_to', models.DateTimeField()),
                ('total_leave_days', models.IntegerField(default=0)),
                ('purpose_of_leave', models.CharField(max_length=50)),
                ('leave_applied_date', models.DateTimeField()),
                ('signature_of_applicant', models.CharField(max_length=30)),
                ('is_approved_supervisor', models.BooleanField(default=False)),
                ('is_approved_hr', models.BooleanField(default=False)),
            ],
        ),
    ]
