# Generated by Django 4.2.7 on 2023-11-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('leaveapp', '0001_initial'), ('leaveapp', '0002_alter_leaverequest_leave_from'), ('leaveapp', '0003_alter_leaverequest_leave_applied_date_and_more'), ('leaveapp', '0004_remove_leaverequest_is_approved_hr_and_more'), ('leaveapp', '0005_rename_is_approved_by_hr_leaverequest_approved_by_hr_and_more'), ('leaveapp', '0006_alter_leaverequest_leave_applied_date')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('department', models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resource'), ('BS', 'Business')], max_length=30)),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('total_leave_days', models.IntegerField(default=0)),
                ('purpose_of_leave', models.CharField(max_length=50)),
                ('leave_applied_date', models.DateField(auto_now_add=True)),
                ('signature_of_applicant', models.CharField(max_length=30)),
                ('approved_by_hr', models.BooleanField(default=False)),
                ('approved_by_supervisor', models.BooleanField(default=False)),
            ],
        ),
    ]
