# Generated by Django 4.2.7 on 2023-11-30 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('department', models.CharField(choices=[('technology', 'Information Technology'), ('finance', 'Finance'), ('support', 'Support'), ('sales', 'Sales')], max_length=30)),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('total_leave_days', models.IntegerField(default=0)),
                ('purpose_of_leave', models.CharField(choices=[('annual_leave', 'Annual Leave'), ('sick_leave', 'Sick Leave'), ('bereavement_leave', 'Bereavement Leave'), ('maternity_leave', 'Maternity Leave'), ('paternity_leave', 'Paternity Leave'), ('others', 'Others')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('leave_applied_date', models.DateField(auto_now_add=True)),
                ('signature_of_applicant', models.CharField(max_length=30)),
                ('approved_by_supervisor', models.BooleanField(default=False)),
                ('approved_by_hr', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
