# Generated by Django 4.2.7 on 2023-11-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_from',
            field=models.DateTimeField(),
        ),
    ]
