# Generated by Django 4.2.7 on 2023-11-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0002_alter_leaverequest_leave_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_applied_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_to',
            field=models.DateField(),
        ),
    ]
