# Generated by Django 4.2.7 on 2023-11-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0003_alter_leaverequest_leave_applied_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='is_approved_hr',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='is_approved_supervisor',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_approved_by_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_approved_by_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
