# Generated by Django 4.2.7 on 2023-11-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0004_remove_leaverequest_is_approved_hr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='is_approved_by_hr',
            new_name='approved_by_hr',
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='is_approved_by_supervisor',
            new_name='approved_by_supervisor',
        ),
    ]
