# Generated by Django 4.2.7 on 2023-11-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0005_rename_is_approved_by_hr_leaverequest_approved_by_hr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_applied_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
