# Generated by Django 4.2.7 on 2023-11-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0007_leaverequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
