# Generated by Django 4.2.7 on 2023-11-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0008_alter_leaverequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='department',
            field=models.CharField(choices=[('technology', 'Information Technology'), ('finance', 'Finance'), ('support', 'Support'), ('sales', 'Sales')], max_length=30),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='purpose_of_leave',
            field=models.CharField(choices=[('annual_leave', 'Annual Leave'), ('sick_leave', 'Sick Leave'), ('bereavement_leave', 'Bereavement Leave'), ('maternity_leave', 'Maternity Leave'), ('paternity_leave', 'Paternity Holiday'), ('others', 'Others')], default='sick_leave', max_length=50),
        ),
    ]
