# Generated by Django 4.2.7 on 2023-11-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0009_leaverequest_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='purpose_of_leave',
            field=models.CharField(choices=[('annual_leave', 'Annual Leave'), ('sick_leave', 'Sick Leave'), ('bereavement_leave', 'Bereavement Leave'), ('maternity_leave', 'Maternity Leave'), ('paternity_leave', 'Paternity Holiday'), ('others', 'Others')], max_length=50),
        ),
    ]
